### ISSUE TITLE
Create an Asset Construct for IPFS

### ISSUE THREAD

**Issue by thantos** [punchcard/cdk3#17]
From #5.

```ts
const myAsset = new IPFSAsset(this, 'myResourceOrDir', {
    path: '...'
});

asset.address
```

https://docs.ipfs.io/

* Should submit an asset to IPFS
* Should contain a deployment time resolvable `address` as a `ref` that contains the asset.
* Should only upload a new version when the content hash changes.

**Comment by thantos** [comment]
How do we write? Thoughts:

* Host with the client running? https://docs.ipfs.io/reference/http/api/#getting-started
* Docker bundler during CDK deployment https://docs.ipfs.io/how-to/run-ipfs-inside-docker/

**Comment by ryan-mars** [comment]
Would be really great if the construct could update IPNS so it always points to the latest deployed asset.
